### ISSUE TITLE
Remove Cryptocat as it is no longer functional

### ISSUE THREAD

**Issue by elationfoundation** [RaReNet/DFAK#39]
Cryptocat is recommended in [secure communications page](https://github.com/RaReNet/DFAK/blob/dd10ead8203808a6114e96a3c47ea97c7bc37225/SecureCommunication.md#safer-communications-what-to-do-when-you-cant-trust-your-communications-channels)  This tool has been [shut down by its creator.](http://web.archive.org/web/20160222145547/https://crypto.cat/) It should be removed.

**Comment by mfc** [comment]
removed mention of cryptocat with: https://github.com/RaReNet/DFAK/pull/40

**Comment by Rafiot** [comment]
Merged, thank you very much for the report.
